### ISSUE TITLE
[BUG] Package file non-existance causes refrapt crash

### ISSUE THREAD

**Issue by mingl0280** [Progeny42/refrapt#10]
**Describe the bug**
When cloning the deb repository `deb [arch=i386] us.archive.ubuntu.com/ubuntu/ focal-security restricted universe`
This directory does not contain a "Packages" file and will cause the refrapt to crash.

Source tree see: [Ubuntu repo](http://us.archive.ubuntu.com/ubuntu/dists/focal-security/restricted/binary-i386/)

**Configuration File and Logs**
```
Sources :  54%|█████████████████████████████████████████████████████████████████▏                                                       | 7/13 [00:09<00:07,  1.31s/ source]
Traceback (most recent call last):                                                                                                                                          
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 220, in main
    Clean()
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 332, in Clean
    ProcessUnmodifiedIndex(key, value)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 505, in ProcessUnmodifiedIndex
    indexFile.Read()
  File "/usr/local/lib/python3.9/dist-packages/refrapt/classes.py", line 538, in Read
    with open(self._path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sources/skel//us.archive.ubuntu.com/ubuntu///dists/focal-security/universe/binary-i386/Packages'
````

**System Information:**
Not needed.

**Comment by Progeny42** [comment]
The `Packages` file should exist, as the `Packages.gz` (preferred format) file is unzipped earlier in the process. I've added the repository and run Refrapt locally, and it succeeded.

Please could your provide the `refrapt.log` file?

**Comment by mingl0280** [comment]
> The `Packages` file should exist, as the `Packages.gz` (preferred format) file is unzipped earlier in the process. I've added the repository and run Refrapt locally, and it succeeded.
> 
> Please could your provide the `refrapt.log` file?

I can't - yesterday I did some very manual fix in the code that tries to decompress those files when it detects the Packages file doesn't exist and it tries to call shell script to uncompress them... However I only saw this issue happen once under the following situation:

- skel / mirror and var directories are completely empty.

If you don't think it's an issue you can close it until I have experienced this again... My repository clone is too large and can't replicate this very easily.
