### ISSUE TITLE
[BUG] Files fail to Download Due to HTTP 503 from Mirror

### ISSUE THREAD

**Issue by Vayano** [Progeny42/refrapt#26]
**Describe the bug**
When I run refrapt --conf /etc/refrapt.refrapt.conf (where my config file is), I get this error :
```
[2022-06-07 19:22:48] INFO: Starting Refrapt process
[2022-06-07 19:22:48] INFO: Removing previous /var files...

[2022-06-07 19:22:48] INFO: Processing 6 Repositories...
[2022-06-07 19:22:48] INFO: Compiled a list of 18 Release files for download
[2022-06-07 19:22:48] INFO: Downloading 18 Release files...
 56%|███████████████████████████████████████████████████████▌                                            | 10/18 [00:03<00:01,  5.56 file/s]Bus error (core dumped)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:04<00:00,  4.24 file/s]

[2022-06-07 19:22:54] INFO: Compiled a list of 1552 Index files for download
[2022-06-07 19:22:54] INFO: Downloading 1552 Index files...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1552/1552 [03:30<00:00,  7.37 file/s]

[2022-06-07 19:26:27] INFO: Decompressing Packages / Sources Indices...
Repositories :  33%|█████████████████████████████                                                          | 2/6 [00:03<00:06,  1.75s/ repo[2022-06-07 19:26:31] WARNING: File 'distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu/dists/jammy-updates/restricted/binary-amd64/Packages' has an unsupported compression format
Repositories : 100%|███████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.01 repo/s]
                                                                                                                                            
[2022-06-07 19:26:33] INFO: Building file list...
Traceback (most recent call last):                                                                                                          
  File "/home/vv/.local/bin/refrapt", line 8, in <module>                                                                                   
    sys.exit(main())                                                                                                                        
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vv/.local/lib/python3.10/site-packages/refrapt/refrapt.py", line 120, in main
    PerformMirroring()
  File "/home/vv/.local/lib/python3.10/site-packages/refrapt/refrapt.py", line 238, in PerformMirroring
    filesToDownload += repository.ParseIndexFiles() 
  File "/home/vv/.local/lib/python3.10/site-packages/refrapt/classes.py", line 361, in ParseIndexFiles
    fileList += self._ProcessIndex(Settings.SkelPath(), file, False)
  File "/home/vv/.local/lib/python3.10/site-packages/refrapt/classes.py", line 436, in _ProcessIndex
    indexFile.Read()
  File "/home/vv/.local/lib/python3.10/site-packages/refrapt/classes.py", line 920, in Read
    self._lines.append(line.decode().rstrip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

**Configuration File and Logs**
Refrapt.conf file : 
```
########################################
###### Refrapt configuration file ######
########################################

##############
## SETTINGS ##
##############
set architecture       = amd64

set rootPath		= "/etc/refrapt/"

set mirrorPath = "/media/vv/2204_repo/testmirror/mirror"

set skelPath = "/media/vv/2204_repo/testmirror/skel"

set varPath = "/media/vv/2204_repo/testmirror/var"

set contents           = true

set threads            = 20

#set authNoChallenge    = false

#set noCheckCertificate = false

#set unlink             = false

#set useProxy           = false

#set httpProxy          = ""

#set httpsProxy         = ""

#set proxyUser          = ""

#set proxyPass          = ""

#set certificate        = "/etc/ssl/certs"

#set caCertificate      = "/etc/ssl/certs"

set privateKey         = 

#set limitRate          = 500m # 500 MB

set language           = "en_GB"

set forceUpdate        = false

set logLevel           = INFO

set test               = false

set byHash             = true

set disableClean       = false

#####################
## REPOSITORY LIST ##
#####################
deb-src [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy main restricted universe multiverse
deb [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy main restricted universe multiverse
deb [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-updates main restricted universe multiverse
deb [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-security main restricted universe multiverse
deb [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-backports main restricted universe multiverse
deb [arch=amd64] http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-proposed main restricted universe multiverse

###################
## DISABLE CLEAN ##
###################
clean=true deb http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy
clean=true deb http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-updates
clean=true deb http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-backports
clean=true deb http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-proposed
clean=true deb http://distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-security
```

**System Information:**
 - OS: Ubuntu 22.04 LTS
 - Refrapt Version 0.4.2

**Comment by Progeny42** [comment]
Well this is an interesting issue. The cause is that the server you are downloading files from is potentially being overloaded by refrapt, so it is responding with HTTP 503. By default, the fetching implementation in refrapt (wget) does not automatically retry if it gets this response, so the file is never downloaded.

Something you can do is use the `limitRate` option in the configuration file, and decrease is to a smaller value, though this will slow down your overall speed, and may be undesirable.

I think the best I can do is the following with regards the downloader:
- Use the `--retry-on-http` for 503. This will allow retries rather than giving up when the server is overloaded.
- Use the `--waitretry=60` to stagger retries in an attempt to reduce the server load
- Increase the `--tries` to 20 to ensure the files are definitely downloaded.

**Comment by Vayano** [comment]
Thank you for the quick response and the patch, it seems to be working now!
