### ISSUE TITLE
[BUG] Default Configuration not created

### ISSUE THREAD

**Issue by kaiszy** [Progeny42/refrapt#30]
**Describe the bug**
When i start refrapt first time i get a exception:

```
~# refrapt
2022-07-26 15:39:39] INFO: Configuration file not found. Creating default...
Traceback (most recent call last):
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 56, in main
    configData = GetConfig(conf)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 327, in GetConfig
    CreateConfig(conf)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 350, in CreateConfig
    with open(defaultConfigPath, "r") as fIn:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/refrapt/refrapt.conf.example'

```

Also call it with a specified conf not working:

```
~# refrapt --conf /tmp/test.conf
[2022-07-26 15:45:01] INFO: Starting Refrapt process
[2022-07-26 15:45:01] INFO: Configuration file not found. Creating default...
Traceback (most recent call last):
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 56, in main
    configData = GetConfig(conf)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 327, in GetConfig
    CreateConfig(conf)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 350, in CreateConfig
    with open(defaultConfigPath, "r") as fIn:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/refrapt/refrapt.conf.example'
```

**Configuration File and Logs**
See above

Installation Log:

```
~# python3.9 -m pip install refrapt
Collecting refrapt
  Downloading Refrapt-0.4.5-py3-none-any.whl (35 kB)
Collecting tendo==0.2.15
  Downloading tendo-0.2.15-py2.py3-none-any.whl (23 kB)
Collecting tqdm>=4.60.0
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 15 kB/s 
Collecting Colorama>=0.4.4
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting filelock==3.0.12
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting Click>=7.1.2
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 25 kB/s 
Collecting wget>=3.2
  Downloading wget-3.2.zip (10 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tendo==0.2.15->refrapt) (45.2.0)
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (from tendo==0.2.15->refrapt) (20.0.2)
Requirement already satisfied: six>=1.7.2 in /usr/lib/python3/dist-packages (from tendo==0.2.15->refrapt) (1.14.0)
Collecting pbr
  Downloading pbr-5.9.0-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 47 kB/s 
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9681 sha256=4bdb0df9db5116a00dfb03fccd9aeca82d4415eed4806ae74869ad9825ae3b08
  Stored in directory: /root/.cache/pip/wheels/04/5f/3e/46cc37c5d698415694d83f607f833f83f0149e49b3af9d0f38
Successfully built wget
Installing collected packages: pbr, tendo, tqdm, Colorama, filelock, Click, wget, refrapt
  Attempting uninstall: Colorama
    Found existing installation: colorama 0.4.3
    Not uninstalling colorama at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'colorama'. No files were found to uninstall.
  Attempting uninstall: Click
    Found existing installation: Click 7.0
    Not uninstalling click at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Click'. No files were found to uninstall.
Successfully installed Click-8.1.3 Colorama-0.4.5 filelock-3.0.12 pbr-5.9.0 refrapt-0.4.5 tendo-0.2.15 tqdm-4.64.0 wget-3.2
```

**System Information:**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

 - Refrapt Version 0.4.5

**Comment by Progeny42** [comment]
Hmm this is strange. The default path to the configuration file should be `~/refrapt`, but yours is `/root/.local/refrapt`.

Just to check, you installed as a normal user, and didn't use `su`?

**Comment by kaiszy** [comment]
Hi,

sorry for late reply.

No, i have installed it as root. I have installed as now as normal user and it works.

Thanks!
