### ISSUE TITLE
[BUG] Refrapt cannot work with flat repository

### ISSUE THREAD

**Issue by mingl0280** [Progeny42/refrapt#9]
**Describe the bug**
When using a remote apt repository like 
`deb [arch=amd64] http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /`
the refrapt cannot recognize the distribution ID as "/" and throws this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 126, in main
    indexFiles += source.GetIndexes()
  File "/usr/local/lib/python3.9/dist-packages/refrapt/classes.py", line 120, in GetIndexes
    self._indexCollection.Add(self._components[0], self._architectures[0], self._uri + "/" + self._distribution + "/Sources" + compressionFormat)
IndexError: list index out of range
```
If the last backslash "/" was removed, you will see it parse correctly, but fail on actual process of index files:

```
[2021-12-28 16:10:23] INFO: Compiled a list of 2765 Index files for download
[2021-12-28 16:10:23] INFO: Downloading 2765 Index files...
100%| 2765/2765 [01:32<00:00, 29.97 file/s]
Traceback (most recent call last):
  File "/usr/local/bin/refrapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/refrapt.py", line 143, in main
    translationFiles += source.GetTranslationIndexes()
  File "/usr/local/lib/python3.9/dist-packages/refrapt/classes.py", line 185, in GetTranslationIndexes
    translationIndexes += self.__ProcessTranslationIndex(baseUrl, component)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/classes.py", line 218, in __ProcessTranslationIndex
    return self.__ProcessIndex(releasePath, IndexType.Release, url, "", component)
  File "/usr/local/lib/python3.9/dist-packages/refrapt/classes.py", line 228, in __ProcessIndex
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sources/skel//developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64//dists//Release'
```

**Configuration File and Logs**
The description already included the line that causes the issue. 

**System Information:**
Not needed.

**Comment by Progeny42** [comment]
I've added proper support for Flat Repositories in the newest release, v0.3.0. I've tested it based on the Repository you've provided.

Please uninstall your existing version of Refrapt, and upgrade to the newest, and close this issue if it is resolved.

Thanks

**Comment by mingl0280** [comment]
> I've added proper support for Flat Repositories in the newest release, v0.3.0. I've tested it based on the Repository you've provided.
> 
> Please uninstall your existing version of Refrapt, and upgrade to the newest, and close this issue if it is resolved.
> 
> Thanks

Sounds good, will test the latest revision.

**Comment by mingl0280** [comment]
The fix works.
